"use strict";

function ERR_INVALID_ARG_TYPE() {
  this.message = "ERR_INVALID_ARG_TYPE";
}
ERR_INVALID_ARG_TYPE.prototype = new Error();

function ERR_INVALID_ARG_VALUE() {
  this.message = "ERR_INVALID_ARG_VALUE";
}
ERR_INVALID_ARG_VALUE.prototype = new Error();

function ERR_PARSE_ARGS_INVALID_OPTION_VALUE() {
  this.message = "ERR_PARSE_ARGS_INVALID_OPTION_VALUE";
}
ERR_PARSE_ARGS_INVALID_OPTION_VALUE.prototype = new Error();

function ERR_PARSE_ARGS_UNKNOWN_OPTION() {
  this.message = "ERR_PARSE_ARGS_UNKNOWN_OPTION";
}
ERR_PARSE_ARGS_UNKNOWN_OPTION.prototype = new Error();

function ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL() {
  this.message = "ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL";
}
ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL.prototype = new Error();

module.exports = {
  codes: {
    ERR_INVALID_ARG_TYPE,
    ERR_INVALID_ARG_VALUE,
    ERR_PARSE_ARGS_INVALID_OPTION_VALUE,
    ERR_PARSE_ARGS_UNKNOWN_OPTION,
    ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL,
  },
};
